import "dotenv/config";
import { writeFile } from "node:fs/promises";
import { hashPassword } from "../lib/auth/password";
import { createSecretToken } from "../lib/auth/tokens";
import type { Role } from "../lib/auth/types";
import type { EmploymentStatusInput } from "../lib/validation/users";

export const demoCredentialFilePath = "LOCAL_CREDENTIALS.md";

type DemoUser = {
  name: string;
  username: string;
  email: string;
  role: Role;
  profile: {
    nationalId?: string;
    shopperId?: string;
    ibsId?: string;
    address?: string;
    employmentStatus: EmploymentStatusInput;
  };
};

type DemoCredential = {
  username: string;
  password: string;
  role: Role;
};

export const demoUsers: DemoUser[] = [
  {
    name: "Demo Super Admin",
    username: "demo.superadmin",
    email: "demo.superadmin@pulse.local",
    role: "SUPER_ADMIN",
    profile: { ibsId: "DEMO-IBS-SA", employmentStatus: "ACTIVE" },
  },
  {
    name: "Demo Admin",
    username: "demo.admin",
    email: "demo.admin@pulse.local",
    role: "ADMIN",
    profile: { ibsId: "DEMO-IBS-ADMIN", employmentStatus: "ACTIVE" },
  },
  {
    name: "Demo Area Manager",
    username: "demo.area",
    email: "demo.area@pulse.local",
    role: "AREA_MANAGER",
    profile: { ibsId: "DEMO-IBS-AM", employmentStatus: "ACTIVE" },
  },
  {
    name: "Demo Champ",
    username: "demo.champ",
    email: "demo.champ@pulse.local",
    role: "CHAMP",
    profile: {
      shopperId: "DEMO-SHOP-CHAMP",
      ibsId: "DEMO-IBS-CHAMP",
      employmentStatus: "ACTIVE",
    },
  },
  {
    name: "Demo Picker",
    username: "demo.picker",
    email: "demo.picker@pulse.local",
    role: "PICKER",
    profile: {
      shopperId: "DEMO-SHOP-PICKER",
      ibsId: "DEMO-IBS-PICKER",
      employmentStatus: "ACTIVE",
    },
  },
];

export function assertDemoSeedAllowed(nodeEnv = process.env.NODE_ENV) {
  if (nodeEnv === "production") {
    throw new Error("Demo users seed cannot run in production.");
  }
}

export function buildDemoCredentialDocument(credentials: DemoCredential[]) {
  const lines = [
    "# Pulse Local Demo Credentials",
    "",
    "Generated by `npm run seed:demo-users`.",
    `This file is intentionally written only to \`${demoCredentialFilePath}\`.`,
    "",
    "| Role | Username | Password |",
    "| --- | --- | --- |",
    ...credentials.map(
      (credential) =>
        `| ${credential.role} | ${credential.username} | ${credential.password} |`,
    ),
    "",
    "All demo users are forced to change password on first login.",
    "",
  ];

  return lines.join("\n");
}

async function main() {
  assertDemoSeedAllowed();

  const [{ PrismaPg }, { PrismaClient }] = await Promise.all([
    import("@prisma/adapter-pg"),
    import("../generated/prisma/client"),
  ]);
  const adapter = new PrismaPg({
    connectionString:
      process.env.DATABASE_URL ??
      "postgresql://pulse_app:replace-with-a-local-password@localhost:5433/pulse_local?schema=public",
  });
  const prisma = new PrismaClient({ adapter });
  const credentials: DemoCredential[] = [];

  try {
    for (const demoUser of demoUsers) {
      const password = `${createSecretToken(12)}Aa1!`;
      const passwordHash = await hashPassword(password);
      const user = await prisma.user.upsert({
        where: { username: demoUser.username },
        update: {
          name: demoUser.name,
          email: demoUser.email,
          role: demoUser.role,
          status: "ACTIVE",
          passwordHash,
          mustChangePassword: true,
          employeeProfile: {
            upsert: {
              create: demoUser.profile,
              update: demoUser.profile,
            },
          },
        },
        create: {
          name: demoUser.name,
          username: demoUser.username,
          email: demoUser.email,
          role: demoUser.role,
          status: "ACTIVE",
          passwordHash,
          mustChangePassword: true,
          employeeProfile: {
            create: demoUser.profile,
          },
        },
        select: { id: true, username: true, role: true },
      });

      await prisma.auditLog.create({
        data: {
          actorUserId: null,
          action: "DEMO_USER_SEEDED",
          entityType: "User",
          entityId: user.id,
          newValueJson: { username: user.username, role: user.role },
        },
      });

      credentials.push({ username: demoUser.username, password, role: demoUser.role });
    }

    await writeFile(
      demoCredentialFilePath,
      buildDemoCredentialDocument(credentials),
      "utf8",
    );
    console.log(
      `Seeded ${credentials.length} demo users. Credentials were written to ${demoCredentialFilePath}.`,
    );
  } finally {
    await prisma.$disconnect();
  }
}

if (process.env.VITEST !== "true") {
  main().catch((error) => {
    console.error(error);
    process.exit(1);
  });
}
